takenet/blip-toolkit

src/components/blipSelect/index.js
Select only show on top if is bigger than the bottom space
=> Select direction

src/scss/components/_input.scss, src/scss/components/_table.scss, src/scss/components/module.scss, src/scss/utilities/_background-color.scss, src/scss/utilities/_border-color.scss, src/scss/utilities/_color.scss, src/scss/variables/_colors.scss, src/scss/variables/_components.scss, src/scss/variables/module.scss
feat(Table): Added bp-table class to Toolkit. Added Whisper color.
=> feat(Table): Added bp-table class to Toolkit. Added Whisper color.

spec/tests/blipInput.spec.js, src/components/blipInput/README.md, src/components/blipInput/index.js
Included a custom validation in the BlipInput component.
=> Included a custom validation in the BlipInput

src/scss/components/_button.scss, src/scss/components/_table.scss, src/scss/utilities/_color.scss, src/scss/variables/_colors.scss, src/scss/variables/_components.scss, src/scss/variables/_globals.scss
adding new colors cloud-burst and athens-gray
adding row hover to table with action
adding style to action icon
adding $u to global variables
feature/146441-adding-action-to-table
=> feat(components): adding new colors and style to action blip table

src/components/blipToasts/README.md
feature/154733-add_toasts_documentation
=> docs(docs): add Blip Toast documentation #154733

src/scss/components/_textarea.scss
ISSUES CLOSED: #152307
feature/152307_new-text-area-component
=> feat(components): add new styles for textarea

src/scss/components/_select.scss
bugfix/155160-make_select_arrow_clickable
=> fix(components): make select arrow clickable. #155160

src/scss/utilities/_gradient.scss, src/scss/variables/_colors.scss
=> fix(components): add more options to suit gradient background rotation

src/components/blipDaterangepicker/index.js
Possibility to change the selectedPeriod on daterangepicker from outside: sdded getter and setter for selectedPeriod
feature/daterangepicker-set-period
=> fix(components): daterangepicker

src/scss/mixins/_button.scss
feat/flat-button
Signed-off-by: Johnatan <johnatan.dias@gmail.com>
=> style(components): fix button icon color in hover

sandbox/blipSelect.js, src/components/blipSelect/CreatableOptionsList.js, src/components/blipSelect/OptionsList.js, src/components/blipSelect/SelectOption.js, src/components/blipSelect/index.js, src/scss/components/_select.scss
feature/158104-add-multiple-to-blip-selected
=> feat(components): adding multiple seletion behaviour to blip-select

src/components/blipSelect/index.js, src/scss/components/_select.scss
feature/158104-add-multiple-to-blip-selected
=> fix(components): fixing select margin

src/scss/components/_input.scss, src/scss/variables/_components.scss
bugfix/159675-fixing-ai-colors
=> fix(components): fixing ai colors

src/scss/components/_toast.scss
=> fix(components): fix toast z-index

sandbox/blipLoading.js, sandbox/index.html, src/components/blipLoading/index.js, src/scss/components/_loading.scss
=> feat(components): adding solid loading circle

src/components/blipLoading/index.js
feature/156899-solid-loading-circle
=> fix(components): adding bp-loading to dotted loading

src/scss/components/_input.scss
New pull request, commited using npm run commit.
feature/157525_checkbox_redesign
=> feat(components): re-design of checkbox component

src/scss/components/_select.scss
feature/165837_move_between_tenants
=> fix(components): fixing add button hover from blip-select

src/scss/components/_select.scss
bugfix/166575-fix-blip-select-description
=> fix(components): fixing blip-select descripting position

src/scss/components/_select.scss
bugfix/166575-fix-blip-select-description
=> fix(components): adjust select description to right

src/components/blipSelect/index.js
feature/166765-add-disabled-option-click-callback
=> feat(components): adding disabled option click callback

sandbox/blipLoading.js, src/components/blipLoading/index.js
=> fix(components): improving blip loading props params

src/components/blipModal/ModalContainer.js
feature/168135_modal_button_color
Changing the color of the button on the modal component.
=> feat(components): modifying modal button background color

build/webpack.prod.conf.js
Modifying minimize config to always minify the files.
=> feat(configs): modifying minimize config to true

build/webpack.prod.conf.js, package.json
Adding uglifyjs plugin to minify the build.
=> feat(configs): adding uglifyjs webpack config

src/scss/components/_daterangepicker.scss
bugfix/183897-fixing-date-picker
=> fix(components): fixing year select behavior in Mozilla

src/components/blipDaterangepicker/index.js
bugfix/fixing-daterangePicker-time-display
=> fix(components): fixing time display

src/components/blipDaterangepicker/index.js
Fixing bug to keep the date and time selected when back to picker.
ISSUES CLOSED: 207374
=> fix(components): when backing to picker keeping time selected before

src/components/blipDatepicker/index.js, src/components/blipDaterangepicker/index.js
when receibing maxrange in period setting limit when user select in daterange
ISSUES CLOSED: #206475
=> feat(components): when receiving maxrange in period setting selection limit

package.json, src/scss/variables/_colors.scss
Changing the colors that are used in IA module for the new ones.
=> style: change color for ia
